### ISSUE TITLE
Error while running 'yarn run dev'

### ISSUE THREAD

**Issue by venkatb4u** [danielr18/react-babel-webpack2#1]
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 ./src/index.jsx
Module not found: Error: Can't resolve 'babel' in '/Users/vsubramanian1/Venkat/myPOCs/react/react-babel-webpack2'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 ./src/index.jsx

**Comment by danielr18** [comment]
Can you check if it's fixed now with #2 ?
